name: Check build & lint errors

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install node@20
        uses: actions/setup-node@v4.0.2
      - name: Install dependencies
        run: npm install
      - name: Test build
        run: npm run build
      - name: Test Lint
        run: npm run lint
